package com.opethic.hrms.HRMSNew.dto;

import com.opethic.hrms.HRMSNew.models.master.*;
import lombok.Data;
import java.lang.String;
import java.util.List;

@Data
public class EmployeeDTO {
    private Long id;
    private String firstName;
    private String middleName;
    private String lastName;
    private String fullName;
    private String address;
    private Long mobileNumber;
    private String gender;
    private String dob;
    private Integer age;
    private String cast;
    private String reasonToJoin;
    private String religion;
    private String marriageStatus;
    private Double height;
    private Double weight;
    private String bloodGroup;
    private Boolean isDisability;
    private String disabilityDetails;
    private Boolean isInjured;
    private String injureDetails;
    private String hobbies;
    private String presentAddress;
    private String permanentAddress;
    private String correspondenceAddress;
    private Double wagesPerDay;
    private Boolean employeeHavePf;
    private Double employerPf;
    private Double employeePf;
    private Boolean employeeHaveEsi;
    private Double employerEsi;
    private Double employeeEsi;
    private Boolean employeeHaveProfTax;
    private Boolean showSalarySheet;
    private Designation designation;
    private Shift shift;
    private Company company;
    private Branch branch;
    private Department department;
    private String emergencyRelation;
    private String emergencyContact;
    private String reportingManager;
    private List<Attendance> attendanceList;
    private List<EmployeeFamily> employeeFamily;
    private List<EmployeeEducation> employeeEducation;
    private List<EmployeeExperienceDetails> employeeExperienceDetails;
    private List<EmployeeDocument> employeeDocuments;
    private List<EmployeeReference> employeeReferences;
    private List<Break> breakList;
    private List<EmployeeLeave> employeeLeaveList;
    private List<EmployeePayroll> employeePayrollList;
    private String wagesOptions;
    private String employeeWagesType;
    private int weeklyOffDay;
    private Boolean isExperienceEmployee;
    private Double expectedSalary;
    private String effectedDate;
    private String doj;
    private String bankName;
    private String branchName;
    private String departmentName;
    private String accountNo;
    private String krapin;
    private String nssf;
    private String nhif;
    private String ifscCode;
    private String pfNumber;
    private String esiNumber;
    private String panNumber;
    private String textPassword;
    private String password;
    private String employeeType;
    private Long createdBy;
    private String createdAt;
    private Long updatedBy;
    private String updatedAt;
    private Boolean status;
}
